apiVersion: v1
kind: LimitRange
metadata:
  name: todoapp-limits
  namespace: todoappns
  labels:
    app: todoapp
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      default:
        cpu: 500m
        memory: 500Mi
