apiVersion: v1
kind: ResourceQuota
metadata:
  name: service1-quota
  namespace: service1
  labels:
    app: service1
spec:
  hard:
    requests.cpu: 1
    requests.memory: 1Gi
    limits.cpu: 2
    limits.memory: 2Gi
    pods: "20"
